# Generated by Django 5.2.10 on 2026-02-11 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['-created_at'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курси'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Mодуль', 'verbose_name_plural': 'Mодулі'},
        ),
        migrations.AddField(
            model_name='courses',
            name='student',
            field=models.ManyToManyField(related_name='student_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
