# Generated by Django 5.2.10 on 2026-02-11 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.ImageField(upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/images/', verbose_name='image')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='video url')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module', verbose_name='lessons')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
                'ordering': ['order'],
                'unique_together': {('module', 'order')},
            },
        ),
    ]
