# Generated by Django 5.2.10 on 2026-03-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
    ]
